### ISSUE TITLE
Production Issues 😞😰

### ISSUE THREAD

**Issue by therealdhrxv** [therealdhruv/Awesome-Links#3]

**Comment by lly02** [comment]
What issue are you facing?

**Comment by therealdhrxv** [comment]
> What issue are you facing?

The hero comp (links should be seen even if the user is not logged in) is not rendering, also the login is not taking to the correct route.

**Comment by Siddhant097** [comment]
@therealdhruv can you assign this issue to me

**Comment by therealdhrxv** [comment]
sure @Siddhant097 👍
