### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jain-anshika** [therealdhruv/Awesome-Links#4]
Assign me this issue under Hacktoberfest . I will create a good readme with steps and project description.

**Comment by therealdhrxv** [comment]
Alright @jain-anshika 👍

**Comment by jain-anshika** [comment]
> Alright @jain-anshika 👍

Please add hacktoberfest label also!!

**Comment by therealdhrxv** [comment]
> > Alright @jain-anshika 👍
> 
> Please add hacktoberfest label also!!

sure, but I don't think that matters really ... as long as the repo has `hacktoberfest` label on it, all PRs merged will be counted ig.

**Comment by jain-anshika** [comment]
Okay, I m new to this so i don't have idea about that... But I will create README soon!!

**Comment by jain-anshika** [comment]
there is a pending PR and it is showing all checks failed.
